# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Heating Loads in Alaska and Beyond
tagline:          ''
description:      'A 2022 Data Science for Social Good summer fellowship project at the University of Washington' 
url:              "https://uwescience.github.io"
baseurl:          "/DSSG2022_heating_loads"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/DSSG-website-template/
